BoxLayout:
    orientation: 'vertical'
    height: 600
    width: 600
    FloatLayout:
        canvas:
            color:
                rgb: app.generate_color
            Ellipse:
                id: orbit
                pos: (center_x, center_y)
                outline_width: 1
                outline_color: 255, 0, 0, 0.2
                color: 0, 0, 0, 0
                size_hint_x: 0
                size_hint_y: 0